# Désactive l'ouverture de la boussole
disable_worlds:
   - 'world_arene'

# Défini le spawn
spawn:
  world: 'world_safe'
  loc: '2.5,107,56.5,180,0'
  
survie:
  world: 'world'
  loc: '264.5,67,-2.5,-90,0'
  
nether:
  world: 'world_nether'
  loc: '17.5,94,36.5,90,0'
  perm: 'group.fer1'
  message: '§e[⚐] §cVous devez être §7[FerI]'
  
ender:
  world: 'world_the_end'
  loc: '9.5,58,-91.5,0,0'
  perm: 'group.or1'
  message: '§e[⚐] §cVous devez être §7[§eOrI§7]'

# Délai de téléportation en seconde
teleportation_delay: 10

# Mondes sans délai de téléportation
worlds_without_delay:
  - 'world_safe'
  - 'world_city'
  - 'world_arene'

home:
  price: 50
  world: 'world'